.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SDL-BALL 6 "October 18, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sdl-ball \- brick-breaking game like DX-Ball/Arkanoid
.SH SYNOPSIS
.B sdl-ball
.SH DESCRIPTION
Your mission: To smash your way through a series of progressively harder
and more tricky levels.
.br
Your tools: Ultrakinetic titanium balls and your trusty
Gruntmazter-3000-Paddle edition.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.SH AUTHOR
sdl-ball was written by Jimmy Christensen <dusted at dusted dot dk>.
.PP
This manual page was written by Evgeni Golov <sargentd@die-welt.net>,
for the Debian project (but may be used by others).
